<a href="https://colab.research.google.com/github/elvoza/Curso-Introductorio-a-Python/blob/main/Sesi%C3%B3n_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="120px" src="https://www.udea.edu.co/wps/wcm/connect/udea/df55724e-3ebc-46c6-b608-fb9206b3fede/facultad-economicas.png?MOD=AJPERES&CVID=nc5zPyj" align="Center" hspace="10px" vspace="10px"></p>


#***Python I - Introducción a modelos económicos y financieros con Python***

---


#**Sesión 3**
# Docente: *Cristian Ruiz Parra*

---
Contenido de la sesión
- Introducción a Numpy
- Operaciones con arreglos matriciales
- principales funciones
- Taller practico

# **Numpy (np)**

NumPy (Numerical Python) es la biblioteca fundamental para computación científica en Python. Proporciona un objeto de arreglo de datos multidimensional de alto rendimiento y herramientas para trabajar con estos "arrays o arreglos".

Primer paso para acceder a Numpy es importarlo

In [195]:
import numpy as np

Recuerda llamarlo con el alias (np) para simplificar el llamar las funciones propias de Numpy

In [196]:
import numpy as np

# 📦 CREACIÓN DE ARRAYS NUMPY
def demostracion_arrays():
    # Desde lista Python
    lista_python = [1, 2, 3, 4, 5]
    array_numpy = np.array(lista_python)

    print("🎯 COMPARACIÓN LISTA vs ARRAY:")
    print(f"Lista Python: {lista_python} (tipo: {type(lista_python)})")
    print(f"Array NumPy:  {array_numpy} (tipo: {type(array_numpy)})")
    print(f"Tipo datos array: {array_numpy.dtype}")
    print(f"Forma del array: {array_numpy.shape}")
    print(f"Dimensiones: {array_numpy.ndim}D")

# Ejecutar demostración
demostracion_arrays()

🎯 COMPARACIÓN LISTA vs ARRAY:
Lista Python: [1, 2, 3, 4, 5] (tipo: <class 'list'>)
Array NumPy:  [1 2 3 4 5] (tipo: <class 'numpy.ndarray'>)
Tipo datos array: int64
Forma del array: (5,)
Dimensiones: 1D


# ¿Por que usar Numpy en lugar de las listas de Python?

La respuesta a esta pregunta es por eficiencia computacional, los algoritmos de Numpy estan implementados en "C" y se encuentran optimizados

In [197]:
import time

def comparacion_velocidad():
    # Datos de ejemplo
    datos = list(range(1000000))
    array_numpy = np.array(datos)

    # Operación con lista Python
    inicio_lista = time.time()
    resultado_lista = [x * 2 for x in datos]
    tiempo_lista = time.time() - inicio_lista

    # Operación con NumPy
    inicio_numpy = time.time()
    resultado_numpy = array_numpy * 2
    tiempo_numpy = time.time() - inicio_numpy

    print("⚡ COMPARACIÓN DE VELOCIDAD:")
    print(f"Lista Python: {tiempo_lista:.6f} segundos")
    print(f"NumPy: {tiempo_numpy:.6f} segundos")
    print(f"NumPy es {tiempo_lista/tiempo_numpy:.1f}x más rápido")
    print(datos[0:10])
    print(array_numpy[0:10])
    print(resultado_lista[0:10])
    print(resultado_numpy[0:10])

comparacion_velocidad()

⚡ COMPARACIÓN DE VELOCIDAD:
Lista Python: 0.055302 segundos
NumPy: 0.004574 segundos
NumPy es 12.1x más rápido
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[ 0  2  4  6  8 10 12 14 16 18]


# **Arreglos de datos**

Existen multiples formas de organizar la información en función de la cantidad de dimensiones de los datos, que podria verse también si existe mayor interacción entre diferentes cantidades de variables y estructuras temporales

¿Cómo conocemos estos arreglos en función de sus dimensiones?

0D:

1D:

2D:

3D:

4D:

## 1D array (vector)

un arreglo unidimensional es una colecion de tipos de datos los cuales se encuntran indexados ( tal y como las listas ). A diferencia de las listas, los arreglos 1D ( y en general los arreglos de cualquier dimension ) solo pueden contener un tipo de dato.

Los arreglos de python soportan indexacion y slicing

para crear un arreglo 1D de python , podemos usar una lista de numpy


In [198]:
v = np.array([1,2,2,5,2.6,5,6,7,3]) #creacion de un arreglo 1D de numpy
print(type(v))
v #Veamos el vector y a que clase pertenece (esto es , veamos que tipo de dato es)

<class 'numpy.ndarray'>


array([1. , 2. , 2. , 5. , 2.6, 5. , 6. , 7. , 3. ])

In [199]:
#indexacion
v[0], v[1] , v[-1] , v[4]

(np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(2.6))

**Formato para llamar subarreglos (Slicing)**

Para llamar una parte de un Arreglo en 1D tenemos el fotmato siguiente:

Nombre del arreglo[Elmento inicial:Elemento final:paso]



In [200]:
#slicing [indice_inicial:indice_fianl:paso]
v[0:7:2], v[::-1] , v[1::3] , v[5::]

(array([1. , 2. , 2.6, 6. ]),
 array([3. , 7. , 6. , 5. , 2.6, 5. , 2. , 2. , 1. ]),
 array([2. , 2.6, 7. ]),
 array([5., 6., 7., 3.]))

**Lista de elementos**

Nombre del arreglo[[Elemento1, elmento2, elemento3,... elementon]]

In [201]:
# otras formas de hacer indexing (usar una lista para hacer indexing)
v[[1,3,5,6]]

array([2., 5., 5., 6.])

**Formato Buleano**
Aquí describiremos que posiciones queremos que conformen nuestro nuevo arreglo

Nombre del arreglo[[(True or false, True or false, True or false, True or false... True or false]]

In [202]:
#Indexacion usando tipos buleanos
v[[True , True , False, False, True, True, False, False, False]]

array([1. , 2. , 2.6, 5. ])

In [203]:
#Indexacion usando tipos buleanos
v > 4

array([False, False, False,  True, False,  True,  True,  True, False])

In [204]:
#Indexacion usando tipos buleanos
v[v > 4]

array([5., 5., 6., 7.])

In [205]:
print(v.shape) #atributo shape del arreglo de numpy (Formato de la matrix)
print(v.dtype) #atributo dtype (Tipos de datos que conforman el arreglo)
print(v.size) #atributo size (cantidad de elementos)
print(v.ndim) #atributo ndim (Dimensiones del arreglo)

(9,)
float64
9
1


## 2D arrays

```
# Tiene formato de código
```



Como se menciono antes, es posible crear arreglos de mayor dimension. en este caso , veamos los arreglos 2D (tambien conocidos como matrices)

In [206]:
#creacion de un arreglo 2D (matriz) usando una lista de python
entradas = [
            [2,6,4,8,9],
            [2,6,7,9,2.3],
            [5,6,3.,4,2.,],
            [9,0,5,3,6,],
            [3.6,2.7,9.8,2,4]
            ]

In [207]:
#creacion de un arreglo 2D (matriz) usando una lista de python
M = np.array(entradas)
M

array([[2. , 6. , 4. , 8. , 9. ],
       [2. , 6. , 7. , 9. , 2.3],
       [5. , 6. , 3. , 4. , 2. ],
       [9. , 0. , 5. , 3. , 6. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [208]:
#Indexacion en arreglos matriciales
M[0,0] , M[4,-1] , M[4,4]

(np.float64(2.0), np.float64(4.0), np.float64(4.0))

In [209]:
#Slicing en arreglos matriciales
# Filas: desde 0 hasta 5, paso 2 | Columna:  0 hasta la 4
M[0:6:2, 0:3]

array([[2. , 6. , 4. ],
       [5. , 6. , 3. ],
       [3.6, 2.7, 9.8]])

In [210]:
#Slicing en arreglos matriciales
# # Filas: 0→6 paso 2 | Columnas: 0→6 paso 2
M[0:6:2, 0:6:2]

array([[2. , 4. , 9. ],
       [5. , 3. , 2. ],
       [3.6, 9.8, 4. ]])

In [211]:
#Slicing en arreglos matriciales
# Filas: 0→6 paso 2 | Columnas: TODAS
M[0:6:2, :]

array([[2. , 6. , 4. , 8. , 9. ],
       [5. , 6. , 3. , 4. , 2. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [212]:
#Slicing en arreglos matriciales
# Filas: TODAS | Columnas: Ultima
M[0:, -1]


array([9. , 2.3, 2. , 6. , 4. ])

In [213]:
#Slicing en arreglos matriciales
#Filas Todas | columas todas con paso 3
M[:, 0:-1:3]

array([[2. , 8. ],
       [2. , 9. ],
       [5. , 4. ],
       [9. , 3. ],
       [3.6, 2. ]])

In [214]:
#Otras formas de indexing usando listas de python
M[:,[0,2,4]]

array([[2. , 4. , 9. ],
       [2. , 7. , 2.3],
       [5. , 3. , 2. ],
       [9. , 5. , 6. ],
       [3.6, 9.8, 4. ]])

In [215]:
#Otras formas de indexing (termino a termino)
index = [[2,2],[0,0]], [[2,2],[0,0]]
M[index]

array([[3., 3.],
       [2., 2.]])

In [216]:
#Indexacion usando tipos buleanos
M > 5

array([[False,  True, False,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True],
       [False, False,  True, False, False]])

In [217]:
#Indexacion usando tipos buleanos
M[M > 5]

array([6. , 8. , 9. , 6. , 7. , 9. , 6. , 9. , 6. , 9.8])

In [218]:
print(M.shape) #atributo shape del arreglo de numpy
print(M.dtype) #atributo dtype
print(M.size) #atributo size
print(M.ndim) #atributo ndim

(5, 5)
float64
25
2


Numpy tiene muchas funciones para crear arreglos

In [219]:
# Creación de un array de zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [220]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [221]:
# Creación de un array de unos
np.ones(5)

array([1., 1., 1., 1., 1.])

In [222]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [223]:
# Creación de un array de una costante
np.full(5 , 3)

array([3, 3, 3, 3, 3])

In [224]:
np.full((3,3,3), 10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [225]:
# Creación de la matriz indentidad de 2x2.
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [226]:
# Crea un vector desde el número inicial 4 hasta el final 10 de 0,2 en 0,2
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [227]:
# Crea un vector de diez valores espaciados la función encuentra el paso
np.linspace(-2,2,10)

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [228]:
# Creación de un arreglo de valores aleatorios dados por una distribucion
#uniforme en el rango (0,1)
np.random.random(10)

array([0.88440147, 0.99830892, 0.79043994, 0.7908426 , 0.79066513,
       0.05182465, 0.16575786, 0.66591013, 0.16052374, 0.06083713])

In [229]:
np.random.random((2,2))

array([[0.90122334, 0.29062136],
       [0.69009536, 0.07324668]])

In [230]:
# Creación arreglo de valores aleatorios dados por una distribucion normal
#loc: Media de la distribución (μ) - default: 0.0
#scale: Desviación estándar (σ) - default: 1.0
#size: Forma del array de salida (int o tupla) - default: None

np.random.normal(loc=5, scale=1, size=10)

array([5.29665334, 5.75261496, 4.3876971 , 4.31607645, 3.88495795,
       5.53729751, 3.4693312 , 6.12597193, 4.3457889 , 5.38193169])

In [231]:
np.random.normal(loc=0, scale=1, size=(3,3))

array([[ 0.12850207, -0.01792221,  1.30043739],
       [ 1.17712024,  1.28005203,  0.73115387],
       [ 1.07949952, -2.61927954, -0.40005265]])

In [232]:
# Creación de una arreglo de números enteros aleatorios dados por una distribucion uniforme en el rango dado
np.random.randint(low = 2, high=10, size=10)

array([5, 2, 7, 5, 6, 5, 6, 5, 4, 3])

In [233]:
np.random.randint(low = 2, high=10, size=(4,4))

array([[4, 7, 9, 5],
       [2, 9, 8, 3],
       [5, 3, 3, 8],
       [2, 3, 5, 2]])

## Ejercicios

\1) Crea una matriz de 3 x 3 con todos los valores true

In [234]:
M = np.ones((3, 3), dtype=bool)
M

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

2) Reemplace todos los numeros impares por -1
```
Input

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```


In [235]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3) Convertir un array de 1D en uno de 2D con dos filas con la misma cantidad de elementos



```
Input:

arr = np.arange(16)
```

ayuda: Investigar el metodo `reshape ` que tienen los arreglos de numpy


In [236]:
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
     

In [237]:
arr = np.arange(16)
arr2 = arr.reshape(2, -1)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

4) Convierte los vectores fila a y b en un vector columna (Apila verticalmente los vectores a y b)

```
Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

ayuda: investigar las funciones np.vstack , np.hstack

In [238]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [239]:

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

ab = np.vstack((a, b)).reshape(-1, 1)
ab

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

5) Identifica los elementos iguales en a y b



```
Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

ayuda: investigar la funcion np.where


In [240]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [241]:
help(np.where)

Help on _ArrayFunctionDispatcher in module numpy:

where(...)
    where(condition, [x, y], /)

    Return elements chosen from `x` or `y` depending on `condition`.

    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.

    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.

    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.

    See Also
    --------
    choose
    nonzero : The function that is called when x and y are om

In [242]:
np.where(a==b)

(array([1, 3, 5, 7]),)

6) Intercambiar las columnas 1 y 2 en el array arr

arr = np.arange(9).reshape(3,3)




```
arr = np.arange(9).reshape(3,3)
```



In [243]:
arr = np.arange(9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [244]:
arr[:, [1, 2]] = arr[:, [2, 1]]
arr

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

## Operaciones basicas entre entre arreglos del mismo tamaño

Las operaciones basicas entre arreglos se dan elemento a elemnto

In [245]:
#definamos los dos arreglos
v = np.random.randint(low = 2, high=10, size=10)
w = np.random.randint(low = 2, high=10, size=10)
v,w

(array([5, 7, 2, 3, 6, 4, 3, 4, 7, 4]), array([8, 6, 2, 4, 9, 8, 6, 7, 8, 9]))

In [246]:
#suma y resta de dos arreglos 1D de la misma longitud
w + v , w - v

(array([13, 13,  4,  7, 15, 12,  9, 11, 15, 13]),
 array([ 3, -1,  0,  1,  3,  4,  3,  3,  1,  5]))

In [247]:
#multiplicacion y division
w*v , w/v

(array([40, 42,  4, 12, 54, 32, 18, 28, 56, 36]),
 array([1.6       , 0.85714286, 1.        , 1.33333333, 1.5       ,
        2.        , 2.        , 1.75      , 1.14285714, 2.25      ]))

In [248]:
#Potenciacion
w**v

array([  32768,  279936,       4,      64,  531441,    4096,     216,
          2401, 2097152,    6561])

In [249]:
#definamos los dos arreglos 2D
v = np.random.randint(low = 2, high=10, size=(3,3))
w = np.random.randint(low = 2, high=10, size=(3,3))
v,w

(array([[7, 2, 9],
        [7, 9, 6],
        [5, 4, 9]]),
 array([[6, 4, 9],
        [8, 5, 9],
        [4, 7, 2]]))

In [250]:
#suma y resta de dos arreglos 1D de la misma longitud
w + v

array([[13,  6, 18],
       [15, 14, 15],
       [ 9, 11, 11]])

In [251]:
#multiplicacion y division
w*v

array([[42,  8, 81],
       [56, 45, 54],
       [20, 28, 18]])

In [252]:
#Potenciacion
w**v

array([[   279936,        16, 387420489],
       [  2097152,   1953125,    531441],
       [     1024,      2401,       512]])

## Operaciones basicas entre entre arreglos de diferente tamaño (Broadcasting)

In [253]:
#definamos un arreglo 1D con numeros aleatorios
v = np.random.randint(low = 2, high=10, size=10)

In [254]:
#suma y resta de un arreglo y una constante
v, v + 1 , v - 1

(array([9, 2, 2, 2, 3, 3, 3, 3, 2, 8]),
 array([10,  3,  3,  3,  4,  4,  4,  4,  3,  9]),
 array([8, 1, 1, 1, 2, 2, 2, 2, 1, 7]))

In [255]:
#multiplicacion  y division de un arreglo y una constante
v*2 , v/2

(array([18,  4,  4,  4,  6,  6,  6,  6,  4, 16]),
 array([4.5, 1. , 1. , 1. , 1.5, 1.5, 1.5, 1.5, 1. , 4. ]))

In [256]:
#Comparaciones entre arreglo y una constante
v > 5

array([ True, False, False, False, False, False, False, False, False,
        True])

In [257]:
#Definamos dos arreglos con diferentes damaños
v = np.random.randint(low = 2, high=10, size=(4,4))
w = np.random.randint(low = 2, high=10, size=(1,4))
v , w

(array([[5, 5, 4, 8],
        [9, 5, 3, 3],
        [8, 6, 4, 3],
        [2, 6, 2, 5]]),
 array([[3, 9, 2, 6]]))

In [258]:
#Suma entre los dos arreglos
w + v

array([[ 8, 14,  6, 14],
       [12, 14,  5,  9],
       [11, 15,  6,  9],
       [ 5, 15,  4, 11]])

In [259]:
#Multiplicacion
w*v

array([[15, 45,  8, 48],
       [27, 45,  6, 18],
       [24, 54,  8, 18],
       [ 6, 54,  4, 30]])

In [260]:
#exponenciacion
w**v

array([[    243,   59049,      16, 1679616],
       [  19683,   59049,       8,     216],
       [   6561,  531441,      16,     216],
       [      9,  531441,       4,    7776]])

## Ufunctions

algunos ejemplso de Ufunctions


In [261]:
#definamos dos arreglos 1D con numeros aleatorios
v = np.random.random(11)
v

array([0.23389485, 0.95313941, 0.08952673, 0.09148798, 0.68414456,
       0.26470009, 0.92225763, 0.64564293, 0.94004922, 0.54336832,
       0.93611111])

In [262]:
v

array([0.23389485, 0.95313941, 0.08952673, 0.09148798, 0.68414456,
       0.26470009, 0.92225763, 0.64564293, 0.94004922, 0.54336832,
       0.93611111])

In [263]:
#sumar las componenetes de un arreglo
np.sum(v)

np.float64(6.304322843220017)

In [264]:
#funciones trigonometricas
np.sin(v)

array([0.23176807, 0.81523764, 0.08940719, 0.09136041, 0.63201031,
       0.26161982, 0.79696731, 0.60171208, 0.80758713, 0.51702211,
       0.80525838])

In [265]:
#exponencial
np.exp(v)

array([1.26351163, 2.59384003, 1.09365657, 1.09580361, 1.98207557,
       1.30304013, 2.51496183, 1.90721284, 2.56010743, 1.72179667,
       2.55004526])

In [266]:
#multiplicacion
np.multiply(v,v)

array([0.0547068 , 0.90847474, 0.00801504, 0.00837005, 0.46805378,
       0.07006614, 0.85055913, 0.41685479, 0.88369254, 0.29524913,
       0.87630401])

In [267]:
#media
np.mean(v)

np.float64(0.5731202584745471)

In [268]:
#desviacion estandar
np.std(v)

np.float64(0.3340129314272643)

## Ejercicios

Para los siguientes ejercicios concidere el suguiente conjunto de datos

In [269]:
#librearia que contiene el conjunto de tados llamados iris
from sklearn.datasets import load_iris

# **Conjunto de datos Iris**

Este conjunto de datos consta de 3 tipos diferentes de iris: (Setosa, Versicolor y Virginica) pétalo y sépalo length, almacenado en una matriz numpy.ndarray de 150x4

Las filas son las muestras y las columnas son: Longitud del sépalo, ancho del sépalo, longitud del pétalo y ancho del pétalo.

El siguiente gráfico utiliza las dos primeras características. Ver aquí para más información sobre este conjunto de datos.

In [270]:
#utilizamos la funcion load_iris() para cargar los datos
dataset = load_iris()

In [271]:
#Inspecciones un poco los datos , tenga encuenta que los datos vienen en forma de diccionario
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [272]:
#veamos la descripcion del data set
dataset['DESCR']

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 

In [273]:
#veamos el nombre de las caracteristicas
dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [274]:
#veamos las etiquetas
dataset['filename']

'iris.csv'

In [275]:
#separemos los datos
X = dataset['data'][: , [0,1]]

In [276]:
X

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.6],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

1) Obtenga el valor maximo y el valor minimo de la matriz X, luego obtenga el valor maximo y minimo de cada una de las columnas (esto es cada una de las caracteristicas)

In [277]:
np.min(X)

np.float64(2.0)

In [278]:
min_y_max= {"sepal_lenght": dataset["data"][: , [0]],
"sepal_width": dataset["data"][: , [1]],
"petal_lenght": dataset["data"][: , [2]],
"petal_width": dataset["data"][: , [3]]}

for nombre, datos in min_y_max.items():
  print(f"{nombre}")
  print(f"min:{np.min(datos)}")
  print(f"max:{np.max(datos)}")



sepal_lenght
min:4.3
max:7.9
sepal_width
min:2.0
max:4.4
petal_lenght
min:1.0
max:6.9
petal_width
min:0.1
max:2.5


2) Obtenga el valor medio, la mediana, la moda y la desviacion estandar para cada una de las caracteristicas
['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [279]:
for nombre, datos in min_y_max.items():
  print(f"{nombre}")
  print(f"media:{np.mean(datos)}")

sepal_lenght
media:5.843333333333334
sepal_width
media:3.0573333333333337
petal_lenght
media:3.7580000000000005
petal_width
media:1.1993333333333336


In [280]:
for nombre, datos in min_y_max.items():
  print(f"{nombre}")
  print(f"mediana:{np.median(datos)}")

sepal_lenght
mediana:5.8
sepal_width
mediana:3.0
petal_lenght
mediana:4.35
petal_width
mediana:1.3


In [281]:
for nombre, datos in min_y_max.items():
  print(f"{nombre}")
  print(f"desviacion:{np.std(datos)}")

sepal_lenght
desviacion:0.8253012917851409
sepal_width
desviacion:0.4344109677354946
petal_lenght
desviacion:1.759404065775303
petal_width
desviacion:0.7596926279021594


3) Para cada una de las caracteristicas identifique:
- la cantidad de valores mayores a las medias
- Extraiga los cuartiles de una de las variables (Recuerde que los cuartiles se calculan con los datos ordenados)

In [282]:
sepal_lenght = dataset["data"][: , [0]]
len(sepal_lenght)
print(sepal_lenght)

[[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]
 [5.4]
 [4.6]
 [5. ]
 [4.4]
 [4.9]
 [5.4]
 [4.8]
 [4.8]
 [4.3]
 [5.8]
 [5.7]
 [5.4]
 [5.1]
 [5.7]
 [5.1]
 [5.4]
 [5.1]
 [4.6]
 [5.1]
 [4.8]
 [5. ]
 [5. ]
 [5.2]
 [5.2]
 [4.7]
 [4.8]
 [5.4]
 [5.2]
 [5.5]
 [4.9]
 [5. ]
 [5.5]
 [4.9]
 [4.4]
 [5.1]
 [5. ]
 [4.5]
 [4.4]
 [5. ]
 [5.1]
 [4.8]
 [5.1]
 [4.6]
 [5.3]
 [5. ]
 [7. ]
 [6.4]
 [6.9]
 [5.5]
 [6.5]
 [5.7]
 [6.3]
 [4.9]
 [6.6]
 [5.2]
 [5. ]
 [5.9]
 [6. ]
 [6.1]
 [5.6]
 [6.7]
 [5.6]
 [5.8]
 [6.2]
 [5.6]
 [5.9]
 [6.1]
 [6.3]
 [6.1]
 [6.4]
 [6.6]
 [6.8]
 [6.7]
 [6. ]
 [5.7]
 [5.5]
 [5.5]
 [5.8]
 [6. ]
 [5.4]
 [6. ]
 [6.7]
 [6.3]
 [5.6]
 [5.5]
 [5.5]
 [6.1]
 [5.8]
 [5. ]
 [5.6]
 [5.7]
 [5.7]
 [6.2]
 [5.1]
 [5.7]
 [6.3]
 [5.8]
 [7.1]
 [6.3]
 [6.5]
 [7.6]
 [4.9]
 [7.3]
 [6.7]
 [7.2]
 [6.5]
 [6.4]
 [6.8]
 [5.7]
 [5.8]
 [6.4]
 [6.5]
 [7.7]
 [7.7]
 [6. ]
 [6.9]
 [5.6]
 [7.7]
 [6.3]
 [6.7]
 [7.2]
 [6.2]
 [6.1]
 [6.4]
 [7.2]
 [7.4]
 [7.9]
 [6.4]
 [6.3]
 [6.1]
 [7.7]
 [6.3]
 [6.4]
 [6. ]
 [6.9]
 [6.7]
 [6.9]
 [5.8]

In [283]:
mediasp=np.mean(sepal_lenght)
mayores=sepal_lenght[sepal_lenght>mediasp]
print("valores de sepal_lenght mayores que su media:")
len(mayores)

valores de sepal_lenght mayores que su media:


70

In [284]:
x= 0

for a in sepal_lenght:

  while a > np.mean(sepal_lenght):
    x+=1
    break
print("valores de sepal_lenght mayores que su media:")
print(x)

valores de sepal_lenght mayores que su media:
70


In [285]:
sepal_width: dataset["data"][: , [1]]
petal_lenght: dataset["data"][: , [2]]
petal_width: dataset["data"][: , [3]]

In [286]:
for nombre, datos in min_y_max.items():
  col=np.ravel(datos)
  mediac=np.mean(col)
  x= 0
  for a in col:
    if a > mediac:
      x+= 1
  print(f"{nombre}:{x} valores por encima de la media")



sepal_lenght:70 valores por encima de la media
sepal_width:67 valores por encima de la media
petal_lenght:93 valores por encima de la media
petal_width:90 valores por encima de la media


In [292]:
for nombre, dato in min_y_max.items():
  col=np.ravel(dato)
  col_ordenada=np.sort(dato)
  p1=np.percentile(col_ordenada,25)
  p2=np.percentile(col_ordenada,50)
  p3=np.percentile(col_ordenada,75)
  p4=np.percentile(col_ordenada,100)
  print(f"{nombre}:el primer cuartil es {p1}")
  print(f"{nombre}:el segundo cuartil es {p2}")
  print(f"{nombre}:el tercer cuartil es {p3}")
  print(f"{nombre}:el ultimo cuartil es {p4}")

sepal_lenght:el primer cuartil es 5.1
sepal_lenght:el segundo cuartil es 5.8
sepal_lenght:el tercer cuartil es 6.4
sepal_lenght:el ultimo cuartil es 7.9
sepal_width:el primer cuartil es 2.8
sepal_width:el segundo cuartil es 3.0
sepal_width:el tercer cuartil es 3.3
sepal_width:el ultimo cuartil es 4.4
petal_lenght:el primer cuartil es 1.6
petal_lenght:el segundo cuartil es 4.35
petal_lenght:el tercer cuartil es 5.1
petal_lenght:el ultimo cuartil es 6.9
petal_width:el primer cuartil es 0.3
petal_width:el segundo cuartil es 1.3
petal_width:el tercer cuartil es 1.8
petal_width:el ultimo cuartil es 2.5


# Bibliografia

- [Documentación Numpy](https://numpy.org/devdocs/index.html)